version: '3'

services:
  mi_postgres:
    image: postgres:latest
    container_name: mi_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: basededatos
    ports:
      - "5555:5432"

  migrador:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mi_postgres
    volumes:
      - ./EventoPass:/app
    working_dir: /app
    command: sh -c "php artisan migrate"